require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb
    - script/**/*
    - vendor/**/*
    - tmp/**/*
    - Guardfile

  TargetRubyVersion: 2.3

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Enabled: false

Rails:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - spec/criterias/**/*
    - spec/requests/**/*
    - spec/solutions/**/*

RSpec/ExampleLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - app/controllers/**/*
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - config/application.rb
    - db/**/*
    - spec/**/*_spec.rb

Style/DotPosition:
  Enabled: true

Style/Encoding:
  Enabled: true
  EnforcedStyle: always

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - 'config/initializers/*'

Style/LambdaCall:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: percent
  Enabled: true

Style/WordArray:
  EnforcedStyle: percent
  Enabled: true
