scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  Comment:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  SelectorDepth:
    max_depth: 4

  StringQuotes:
    style: double_quotes
